apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ni8xoeef1-python
  janus-idp.io/tekton: ni8xoeef1-python
  backstage.io/kubernetes-id: ni8xoeef1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ni8xoeef1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
